# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - HolaJs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_3b281ced751b48ec8cd601b273af1515 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7bae1b3b17ec4bbbb9cef4b0302c55b4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3b281ced751b48ec8cd601b273af1515 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'HolaJs'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d96c416b4eda450884cf044a030da8b9 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3b281ced751b48ec8cd601b273af1515 }}/appsvc/staticsite:${{ github.sha }}'